### PR TITLE
New Design Changes

### PR DESCRIPTION
**Pull request by Sujith-Barve**
@Prashant-Mutnale

### CODE REVIEW

**Comment by amarts** [comment]
where can I see the page?

**Comment by Prashant-Mutnale** [comment]
> where can I see the page?

Will push this to github pages and send the link

**Comment by Prashant-Mutnale** [comment]
> where can I see the page?

https://prashant-mutnale.github.io/cord-network.github.io/new-cord.html

**Comment by Prashant-Mutnale** [comment]
We can close this Pr as this changes are included in this PR #14

**Comment by Sujith-Barve** [comment]
Included in another pr

**Pull request closed without merging**
